In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
import pandas as pd
import pickle
from sklearn.feature_extraction import DictVectorizer

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/kejihela/DataTalksclubProject/master/dataset/flight_dataset.csv")
df

,Airline,Source,Destination,Total_Stops,Price,Date,Month,Year,Dep_hours,Dep_min,Arrival_hours,Arrival_min,Duration_hours,Duration_min
0,IndiGo,Banglore,New Delhi,0,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,2,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,2,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,1,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,1,13302,1,3,2019,16,50,21,35,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,0,4107,9,4,2019,19,55,22,25,2,30
10679,Air India,Kolkata,Banglore,0,4145,27,4,2019,20,45,23,20,2,35
10680,Jet Airways,Banglore,Delhi,0,7229,27,4,2019,8,20,11,20,3,0
10681,Vistara,Banglore,New Delhi,0,12648,1,3,2019,11,30,14,10,2,40
10682,Air India,Delhi,Cochin,2,11753,9,5,2019,10,55,19,15,8,20

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Airline         10683 non-null  object
 1   Source          10683 non-null  object
 2   Destination     10683 non-null  object
 3   Total_Stops     10683 non-null  int64
 4   Price           10683 non-null  int64
 5   Date            10683 non-null  int64
 6   Month           10683 non-null  int64
 7   Year            10683 non-null  int64
 8   Dep_hours       10683 non-null  int64
 9   Dep_min         10683 non-null  int64
 10  Arrival_hours   10683 non-null  int64
 11  Arrival_min     10683 non-null  int64
 12  Duration_hours  10683 non-null  int64
 13  Duration_min    10683 non-null  int64
dtypes: int64(11), object(3)
memory usage: 1.1+ MB

In [4]:
categorical = ["Airline", "Source", "Destination"]
numerical = ["Total_Stops","Duration_hours","Duration_min"]

In [5]:
df = df[categorical + numerical]
df

,Airline,Source,Destination,Total_Stops,Duration_hours,Duration_min
0,IndiGo,Banglore,New Delhi,0,2,50
1,Air India,Kolkata,Banglore,2,7,25
2,Jet Airways,Delhi,Cochin,2,19,0
3,IndiGo,Kolkata,Banglore,1,5,25
4,IndiGo,Banglore,New Delhi,1,4,45
...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,0,2,30
10679,Air India,Kolkata,Banglore,0,2,35
10680,Jet Airways,Banglore,Delhi,0,3,0
10681,Vistara,Banglore,New Delhi,0,2,40
10682,Air India,Delhi,Cochin,2,8,20

In [6]:
df.Duration_hours = df.Duration_hours *60
df

/tmp/ipykernel_4222/4098694595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Duration_hours = df.Duration_hours *60

,Airline,Source,Destination,Total_Stops,Duration_hours,Duration_min
0,IndiGo,Banglore,New Delhi,0,120,50
1,Air India,Kolkata,Banglore,2,420,25
2,Jet Airways,Delhi,Cochin,2,1140,0
3,IndiGo,Kolkata,Banglore,1,300,25
4,IndiGo,Banglore,New Delhi,1,240,45
...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,0,120,30
10679,Air India,Kolkata,Banglore,0,120,35
10680,Jet Airways,Banglore,Delhi,0,180,0
10681,Vistara,Banglore,New Delhi,0,120,40
10682,Air India,Delhi,Cochin,2,480,20

In [7]:
df["duration"] = df["Duration_hours"] + df["Duration_min"]
df

/tmp/ipykernel_4222/3890359722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["duration"] = df["Duration_hours"] + df["Duration_min"]

,Airline,Source,Destination,Total_Stops,Duration_hours,Duration_min,duration
0,IndiGo,Banglore,New Delhi,0,120,50,170
1,Air India,Kolkata,Banglore,2,420,25,445
2,Jet Airways,Delhi,Cochin,2,1140,0,1140
3,IndiGo,Kolkata,Banglore,1,300,25,325
4,IndiGo,Banglore,New Delhi,1,240,45,285
...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,0,120,30,150
10679,Air India,Kolkata,Banglore,0,120,35,155
10680,Jet Airways,Banglore,Delhi,0,180,0,180
10681,Vistara,Banglore,New Delhi,0,120,40,160
10682,Air India,Delhi,Cochin,2,480,20,500

In [ ]:
df = df.drop(["Duration_hours", "Duration_min", "duration"], axis = 1)
df

In [8]:
target = df["duration"].values

In [9]:
df = df.to_dict(orient = "records")

In [13]:
dv = DictVectorizer()
df = dv.fit_transform(df)

In [14]:
train_df = df[:8000]
test_df = df[8000:]
y_train =  target[:8000]
y_test = target[8000:]

In [15]:
model = LinearRegression()
model.fit(train_df, y_train)

LinearRegression()

In [32]:
train_pred = model.predict(train_df)

In [18]:
mean_absolute_error(train_pred, y_train)

np.float64(0.0005153618839878469)

In [21]:
val_df = pd.DataFrame()

In [22]:
val_pred = model.predict(test_df)
val_df["prediction"] = val_pred

In [23]:
mean_absolute_error(val_pred, y_test)

np.float64(0.0005155412528269134)

In [26]:
with open('models/linear_reg.bin','wb') as f_out:
    pickle.dump(model, f_out)

In [28]:
val_df.to_csv("data/reference.csv")